language: node_js
node_js:
  - stable
install:
  - npm install

script:
  - npx prettier@2.0.2 -c library/stack.js
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
