language: node_js
node_js:
  - stable
install:
  - npm install

script:
  - npm run cover

git:
  - autocrlf: npx prettier@2.0.2 --check "**/*.js"

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
